name: roulette
description: Forked from https://github.com/do9core/roulette
version: 0.2.0
repository: https://github.com/Skeletonek/roulette

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  touchable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

